### ISSUE TITLE
UI bug spotted in pagination part

### ISSUE THREAD

**Issue by baoc75** [vanguardapp/activity-log#4]
![image](https://user-images.githubusercontent.com/8294297/128154864-bc132313-1170-4f0c-a0c7-93155b9920d8.png)

**Comment by loshmis** [comment]
@baoc75 Thanks for reporting a bug. There is a new version of Vanguard waiting for Envato review which should address this issue. 

In the meantime, you can easily fix it by adding the following line of code at the bottom of the `boot` method in `app/Providers/AppServiceProvider.php` file:

```php
\Illuminate\Pagination\Paginator::useBootstrap();
```
